apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: yoctobuild
  namespace: jenkins
spec:
  containers:
  - name: crops
    image: crops/yocto:ubuntu-22.04-base # crops/yocto
    imagePullPolicy: "Always"
    command:
    - sleep
    args:
    - 99d
