apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: yoctobuild
  namespace: jenkins
spec:
  containers:
  - name: crops
    image: fedora # crops/poky
    imagePullPolicy: "Always"
    command:
    - sleep
    args:
    - 99d
