apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: yoctobuild
  namespace: jenkins
spec:
  containers:
  - name: crops
    image: crops/yocto:ubuntu-22.04-base # crops/yocto
    imagePullPolicy: "Always"
    resources:
      limits:
        cpu: "12"
        memory: "6000Mi"
      requests:
        cpu: 10000m
        memory: "4000Mi"
    command:
    - sleep
    args:
    - 99d
